FROM node:16 as build
WORKDIR /workspace
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /workspace/build /usr/share/nginx/html